name: Birthday Reminder

on:
  schedule:
    - cron: '0 6,18 * * *'  # Runs at 06:00 and 18:00 UTC daily
  workflow_dispatch:

jobs:
  send_reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run birthday reminder script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python birthday_reminder.py
